stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - apt-get update && apt-get install make
  script:
    - echo "Beginning compile"
    - make
    - echo "Compile complete."
  artifacts:
    paths:
      - wacc-42-compiler.jar

test-setup-job:
  stage: test
  script:
    - rm -rf wacc_examples
    - git clone https://gitlab.doc.ic.ac.uk/ard21/wacc_examples.git
  artifacts:
    paths:
      - wacc_examples
      - wacc-42-compiler.jar

valid-frontend-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  needs: [test-setup-job]
  script:
    - echo "Running valid test cases..."
    - sbt "testOnly wacc.ValidFrontendTests"
    - echo "Tests complete"

invalid-syntax-error-test-job:
  stage: test    # It only starts when the job in the build stage completes successfully.
  needs: [test-setup-job]
  script:
    - echo "Running invalid syntax error test cases..."
    - sbt "testOnly wacc.InvalidSyntaxErrorTests"
    - echo "Tests complete"

invalid-semantic-error-test-job:
  stage: test    # It only starts when the job in the build stage completes successfully.
  needs: [test-setup-job]
  script:
    - echo "Running invalid semantic error test cases..."
    - sbt "testOnly wacc.InvalidSemanticErrorTests"
    - echo "Tests complete"

extension-unit-test-job:
  stage: test
  script:
    - sbt "testOnly wacc.InlineFunctionsUnitTests"
    - sbt "testOnly wacc.PeepholeUnitTests"
    - sbt "testOnly wacc.SemanticAnalysisUnitTests"
  
backend-test-job:
  stage: test
  needs: [test-setup-job]
  script:
    - echo "Running backend test cases..."
    - sbt "testOnly wacc.BackendTests"
    - echo "Tests complete"

test-cleanup-job:
  stage: test
  needs: [valid-frontend-test-job, invalid-syntax-error-test-job, invalid-semantic-error-test-job, backend-test-job]
  script:
    - rm -rf wacc_examples
